#Set how much the Estus Flask heals by default, 1 = half a heart, default:6
#Range: 0.0 ~ 1.7976931348623157E308
"Estus Flask Base Heal" = 20
#Set the amount to increase Estus Flask healing per level, default:1
#Range: 0.0 ~ 1.7976931348623157E308
"Estus Flask Heal Per Level" = 1.0
#Set the amount to increase damage for reinforced tools per level, default:0.5
#Range: 0.0 ~ 1.7976931348623157E308
"Reinforce Damage Per Level" = 1

