#The default element.
defaultElement = "normal"
#The default style.
defaultStyle = "slash"
#The maximal combat factor. See vanilla Enchantment Protection Factor.
#Range: 1 ~ 200
maxFactor = 120
#Scaling for (style) protection enchantments. See vanilla Enchantment Protection Factor.
#Range: 1 ~ 15
enchantmentScaling = 1

