#When a chest is generated in a supported structure it will have a 1/x chance of being a mimic. Higher value means fewer mimics. A value of 1 means always a mimic.
#Range: > 1
mimicSpawnChance = 5
#When true, the location of mimic spawns will be logged.
debugMode = false

