# naturalabsorption:absorption.toml
# This config contains most options for features that apply to absorption (yellow hearts).
# Does NOT contain any armor or enchantment options - see the 'enchant_and_armor' config for those.
# Also contains hunger options related specifically to absorption recovery.


# Category: absorption
# Options that apply to absorption (yellow hearts) from any source.
# 
# Note: All absorption amounts are in half-hearts.

	# The total maximum absorption a player may obtain from (almost) all sources combined.
	# This limit is ignored by potion effects. If this is set less than 0, the limit is disabled.
	# <Number> Range: Any Value, Default: -1.0
	absorption.global_maximum = -1.0

	# Players will respawn with up to this much absorption, limited by their personal max absorption.
	# <Number> Range: ≥ 0.0, Default: 0.0
	absorption.respawn_amount = 0.0

	# The amount of time (in ticks) a player must go without taking damage before their absorption begins
	# to recover (20 ticks = 1 second). If this is set less than 0, players will not naturally recover lost absorption.
	# <Integer> Range: ≥ -1, Default: 120
	absorption.recovery.delay = 140
	# The amount of absorption regenerated each second while recovering (in half-hearts/second).
	# <Number> Range: ≥ 0.0, Default: 2.0
	absorption.recovery.rate = 2.0

	# Players need to have at least this much hunger (in half-drumsticks) to regenerate absorption.
	# <Integer> Range: ≥ 0, Default: 0
	absorption.recovery.hunger_required = 0
	# The amount of hunger drained for each absorption regenerated (in drumsticks/heart).
	# Players can't lose over 1/2 drumstick per game tick or more than 5 drumsticks of hunger per recovery tick.
	# <Number> Range: ≥ 0.0, Default: 0.0
	absorption.recovery.hunger_cost = 0.0

	# NOTE: This option is not compatible with a lot of mods that do their own heart rendering stuff. For instance, Mantle's heart stacker option that stacks hearts instead of vanilla drawing multiple rows, will break this feature.
	# If true, the mod will render the empty heart background behind absorption hearts you are missing,
	# but can regenerate back. This may not work right if another mod changes heart bar rendering.
	# <Boolean> Valid Values: { true, false }, Default: true
	absorption.render_capacity_background = true


# Category: natural_absorption
# Options for natural absorption. Not to be confused with the Natural Absorption mod itself.
# Natural absorption is one source of maximum absorption that is innate to the player - it does not
# come from any items or potions/effects.
# By default, each player starts with some natural absorption, gains more by crafting and consuming
# Books of Absorption, and loses some upon death.
# 
# Note: All absorption amounts are in half-hearts.

	# The amount of natural absorption a new player starts with.
	# <Number> Range: ≥ 0.0, Default: 4.0
	natural_absorption.starting_absorption = 10.0
	# The maximum natural absorption a player may obtain from upgrades.
	# Does not include any other sources of max absorption (such as from potions or equipment).
	# <Number> Range: ≥ 0.0, Default: 20.0
	natural_absorption.max_absorption = 50.0

	# The amount of maximum absorption a player loses with each death. Will not drop below the death penalty limit.
	# <Number> Range: ≥ 0.0, Default: 2.0
	natural_absorption.death_penalty = 10.0
	# A player will not drop below this much max absorption due to death penalty.
	# <Number> Range: ≥ 0.0, Default: 10.0
	natural_absorption.death_penalty_limit = 25.0

	# The amount of maximum natural absorption gained from each upgrade.
	# Set this to 0 to disable upgrades.
	# <Number> Range: ≥ 0.0, Default: 2.0
	natural_absorption.upgrades.gain = 2.0

	# The base number of levels required to use a Book of Absorption.
	# A negative value reduces the cost of the first upgrade(s).
	# The final level cost is rounded down to the nearest whole number and clamped between 0 and the cost limit.
	# <Number> Range: Any Value, Default: 0.0
	natural_absorption.level_cost.base = 0.0
	# The number of levels required to use a Book of Absorption for each point of natural absorption
	# the player already has.
	# <Number> Range: ≥ 0.0, Default: 2.5
	natural_absorption.level_cost.per_point = 2.5
	# The maximum number of levels that can be required to use a Book of Absorption.
	# Set this to 0 to disable level costs entirely.
	# <Integer> Range: ≥ 0, Default: 30
	natural_absorption.level_cost.limit = 10

	# The recipe for making a Book of Absorption.
	#   none     - <no recipe>
	#   simple   - aB  (book + apple, shapeless)
	#   sandwich - aBa (book + 2 apples)
	#   cross    -  a  (book + 4 apples)
	#              aBa 
	#               a  
	#   surround - aaa (book + 8 apples)
	#              aBa 
	#              aaa 
	# B = book & quill, a = golden apple
	# <Enum> Valid Values: { "none", "simple", "sandwich", "cross", "surround" }, Default: "cross"
	natural_absorption.upgrade_book.recipe = "none"
	# Set to true to display current and max natural absorption on the Book of Absorption tooltip.
	# Particularly helpful if you must disable the heart background rendering.
	# <Boolean> Valid Values: { true, false }, Default: false
	natural_absorption.upgrade_book.extra_tooltip_info = false

	# If enabled, players can use the glorious Absorption Absorbing Book to convert some of their natural
	# absorption back into an absorption book. The natural absorption lost per use is exactly one upgrade.
	# <Boolean> Valid Values: { true, false }, Default: true
	natural_absorption.downgrade_book.enabled = true
	# The percentage of the experience levels refunded when using an Absorption Absorbing Book.
	# For example, a value of 0.5 (50%) will restore half of the levels consumed by a Book of Absorption,
	# rounded down to the nearest whole number.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.75
	natural_absorption.downgrade_book.level_refund = 0.75
	# If enabled, a Book of Absorption will be refunded when using an Absorption Absorbing Book.
	# <Boolean> Valid Values: { true, false }, Default: true
	natural_absorption.downgrade_book.book_refund = true
