
#Settings for the mod's added generation
[world]

	[world.aluminum]
		#Generate Aluminum Ore
		generate_aluminum = true
		#Density of Aluminum Ore
		#Range: 1 ~ 40
		aluminum_density = 15
		#Vein size of Aluminum Ore
		#Range: 1 ~ 60
		aluminum_size = 9
		#Minimum Y Level to Generate Aluminum
		#Range: 1 ~ 256
		aluminum_min_y = 25
		#Maximum Y Level to Generate Aluminum
		#Range: 1 ~ 256
		aluminum_max_y = 55

	[world.cadmium]
		#Generate Cadmium Ore
		generate_cadmium = true
		#Density of Cadmium Ore
		#Range: 1 ~ 40
		cadmium_density = 5
		#Vein size of Cadmium Ore
		#Range: 1 ~ 60
		cadmium_size = 7
		#Minimum Y Level to Cadmium Aluminum
		#Range: 1 ~ 256
		cadmium_min_y = 30
		#Maximum Y Level to Cadmium Aluminum
		#Range: 1 ~ 256
		cadmium_max_y = 50

	[world.chromium]
		#Generate Chromium Ore
		generate_chromium = true
		#Density of Chromium Ore
		#Range: 1 ~ 40
		chromium_density = 8
		#Vein size of Chromium Ore
		#Range: 1 ~ 60
		chromium_size = 6
		#Minimum Y Level to Generate Chromium
		#Range: 1 ~ 256
		chromium_min_y = 20
		#Maximum Y Level to Generate Chromium
		#Range: 1 ~ 256
		chromium_max_y = 45

	[world.copper]
		#Generate Copper Ore
		generate_copper = true
		#Density of Copper Ore
		#Range: 1 ~ 40
		copper_density = 15
		#Vein size of Copper Ore
		#Range: 1 ~ 60
		copper_size = 9
		#Minimum Y Level to Generate Copper
		#Range: 1 ~ 256
		copper_min_y = 30
		#Maximum Y Level to Generate Copper
		#Range: 1 ~ 256
		copper_max_y = 70

	[world.lead]
		#Generate Lead Ore
		generate_lead = true
		#Density of Lead Ore
		#Range: 1 ~ 40
		lead_density = 15
		#Vein size of Lead Ore
		#Range: 1 ~ 60
		lead_size = 9
		#Minimum Y Level to Generate Lead
		#Range: 1 ~ 256
		lead_min_y = 20
		#Maximum Y Level to Generate Lead
		#Range: 1 ~ 256
		lead_max_y = 40

	[world.silver]
		#Generate Silver Ore
		generate_silver = true
		#Density of Silver Ore
		#Range: 1 ~ 40
		silver_density = 11
		#Vein size of Silver Ore
		#Range: 1 ~ 60
		silver_size = 7
		#Minimum Y Level to Generate Silver
		#Range: 1 ~ 256
		silver_min_y = 16
		#Maximum Y Level to Generate Silver
		#Range: 1 ~ 256
		silver_max_y = 46

	[world.tin]
		#Generate Tin Ore
		generate_tin = true
		#Density of Tin Ore
		#Range: 1 ~ 40
		tin_density = 15
		#Vein size of Tin Ore
		#Range: 1 ~ 60
		tin_size = 11
		#Minimum Y Level to Generate Tin
		#Range: 1 ~ 256
		tin_min_y = 40
		#Maximum Y Level to Generate Tin
		#Range: 1 ~ 256
		tin_max_y = 80

	[world.zinc]
		#Generate Zinc Ore
		generate_zinc = true
		#Density of Zinc Ore
		#Range: 1 ~ 40
		zinc_density = 12
		#Vein size of Zinc Ore
		#Range: 1 ~ 60
		zinc_size = 8
		#Minimum Y Level to Generate Zinc
		#Range: 1 ~ 256
		zinc_min_y = 20
		#Maximum Y Level to Generate Zinc
		#Range: 1 ~ 256
		zinc_max_y = 40

	[world.loot]
		#Add Lerasium to dungeon and other loot tables
		generate_lerasium = true
		#Add Unbreakable Obsidian Daggers to end city and other loot tables
		generate_unbreakable_daggers = true

#Settings for the gameplay elements of the mod
[gameplay]
	#Spawn players as a random Misting
	random_mistings = true
	#Regenerate the metal whitelist
	regenerate_whitelist = false
	#List of registry names of items and blocks that are counted as 'metal
	whitelist = ["allomancy:allomantic_grinder", "allomancy:bendalloy_block", "allomancy:bendalloy_flakes", "allomancy:bendalloy_ingot", "allomancy:bendalloy_nugget", "allomancy:bendalloy_pattern", "allomancy:brass_block", "allomancy:brass_flakes", "allomancy:brass_ingot", "allomancy:brass_nugget", "allomancy:brass_pattern", "allomancy:bronze_block", "allomancy:bronze_flakes", "allomancy:bronze_ingot", "allomancy:bronze_nugget", "allomancy:bronze_pattern", "allomancy:cadmium_block", "allomancy:cadmium_flakes", "allomancy:cadmium_ingot", "allomancy:cadmium_nugget", "allomancy:cadmium_ore", "allomancy:cadmium_pattern", "allomancy:chromium_block", "allomancy:chromium_flakes", "allomancy:chromium_ingot", "allomancy:chromium_nugget", "allomancy:chromium_ore", "allomancy:chromium_pattern", "allomancy:coin_bag", "allomancy:copper_block", "allomancy:copper_flakes", "allomancy:copper_ingot", "allomancy:copper_nugget", "allomancy:copper_ore", "allomancy:copper_pattern", "allomancy:duralumin_block", "allomancy:duralumin_flakes", "allomancy:duralumin_ingot", "allomancy:duralumin_nugget", "allomancy:duralumin_pattern", "allomancy:electrum_block", "allomancy:electrum_flakes", "allomancy:electrum_ingot", "allomancy:electrum_nugget", "allomancy:electrum_pattern", "allomancy:gold_flakes", "allomancy:gold_pattern", "allomancy:iron_button", "allomancy:iron_flakes", "allomancy:iron_lever", "allomancy:iron_pattern", "allomancy:lead_block", "allomancy:lead_flakes", "allomancy:lead_ingot", "allomancy:lead_nugget", "allomancy:lead_ore", "allomancy:lerasium_nugget", "allomancy:nicrosil_block", "allomancy:nicrosil_flakes", "allomancy:nicrosil_ingot", "allomancy:nicrosil_nugget", "allomancy:nicrosil_pattern", "allomancy:pewter_block", "allomancy:pewter_flakes", "allomancy:pewter_ingot", "allomancy:pewter_nugget", "allomancy:pewter_pattern", "allomancy:silver_block", "allomancy:silver_flakes", "allomancy:silver_ingot", "allomancy:silver_nugget", "allomancy:silver_ore", "allomancy:steel_block", "allomancy:steel_flakes", "allomancy:steel_ingot", "allomancy:steel_nugget", "allomancy:steel_pattern", "allomancy:tin_block", "allomancy:tin_flakes", "allomancy:tin_ingot", "allomancy:tin_nugget", "allomancy:tin_ore", "allomancy:tin_pattern", "allomancy:vial", "allomancy:zinc_block", "allomancy:zinc_flakes", "allomancy:zinc_ingot", "allomancy:zinc_nugget", "allomancy:zinc_ore", "allomancy:zinc_pattern", "animalbikes:irongolembike", "animalbikes:silverfishbike", "appliedenergistics2:gold_dust", "appliedenergistics2:iron_dust", "aquamirae:golden_moth_in_a_jar", "aquamirae:golden_moth_spawn_egg", "bountifulbaubles:gloves_digging_iron", "byg:blue_nether_gold_ore", "byg:brimstone_nether_gold_ore", "byg:golden_spined_cactus", "byg:potted_golden_spined_cactus", "byg:potted_silver_maple_sapling", "byg:potted_silver_vase_flower", "byg:silver_maple_leaves", "byg:silver_maple_sapling", "byg:silver_vase_flower", "charm:gold_bars", "charm:gold_chain", "charm:gold_lantern", "charm:gold_soul_lantern", "enigmaticlegacy:iron_ring", "epicfight:golden_dagger", "epicfight:golden_greatsword", "epicfight:golden_longsword", "epicfight:golden_spear", "epicfight:golden_tachi", "epicfight:iron_dagger", "epicfight:iron_greatsword", "epicfight:iron_longsword", "epicfight:iron_spear", "epicfight:iron_tachi", "expandedstorage:gold_barrel", "expandedstorage:gold_chest", "expandedstorage:gold_to_diamond_conversion_kit", "expandedstorage:gold_to_netherite_conversion_kit", "expandedstorage:gold_to_obsidian_conversion_kit", "expandedstorage:iron_barrel", "expandedstorage:iron_chest", "expandedstorage:iron_to_diamond_conversion_kit", "expandedstorage:iron_to_gold_conversion_kit", "expandedstorage:iron_to_netherite_conversion_kit", "expandedstorage:iron_to_obsidian_conversion_kit", "expandedstorage:old_gold_chest", "expandedstorage:old_iron_chest", "expandedstorage:wood_to_gold_conversion_kit", "expandedstorage:wood_to_iron_conversion_kit", "extcaves:iron_dagger", "extcaves:mushroom_goldishroom", "golemania:golden_golem_spawn_egg", "golemania:iron_golem_spawn_egg", "gunswithoutroses:gold_gun", "gunswithoutroses:iron_bullet", "gunswithoutroses:iron_gun", "illagers_plus:black_iron_golem_egg", "locks:gold_lock", "locks:gold_lock_pick", "locks:iron_lock", "locks:iron_lock_mechanism", "locks:iron_lock_pick", "locks:steel_lock", "locks:steel_lock_mechanism", "locks:steel_lock_pick", "meetyourfight:ace_of_iron", "minecraft:activator_rail", "minecraft:ancient_debris", "minecraft:anvil", "minecraft:bell", "minecraft:blast_furnace", "minecraft:bucket", "minecraft:cauldron", "minecraft:chain", "minecraft:chainmail_boots", "minecraft:chainmail_chestplate", "minecraft:chainmail_helmet", "minecraft:chainmail_leggings", "minecraft:chest_minecart", "minecraft:chipped_anvil", "minecraft:clock", "minecraft:cod_bucket", "minecraft:compass", "minecraft:crossbow", "minecraft:damaged_anvil", "minecraft:detector_rail", "minecraft:enchanted_golden_apple", "minecraft:flint_and_steel", "minecraft:furnace_minecart", "minecraft:gilded_blackstone", "minecraft:gold_block", "minecraft:gold_ingot", "minecraft:gold_nugget", "minecraft:gold_ore", "minecraft:golden_apple", "minecraft:golden_axe", "minecraft:golden_boots", "minecraft:golden_carrot", "minecraft:golden_chestplate", "minecraft:golden_helmet", "minecraft:golden_hoe", "minecraft:golden_horse_armor", "minecraft:golden_leggings", "minecraft:golden_pickaxe", "minecraft:golden_shovel", "minecraft:golden_sword", "minecraft:heavy_weighted_pressure_plate", "minecraft:hopper", "minecraft:hopper_minecart", "minecraft:iron_axe", "minecraft:iron_bars", "minecraft:iron_block", "minecraft:iron_boots", "minecraft:iron_chestplate", "minecraft:iron_door", "minecraft:iron_helmet", "minecraft:iron_hoe", "minecraft:iron_horse_armor", "minecraft:iron_ingot", "minecraft:iron_leggings", "minecraft:iron_nugget", "minecraft:iron_ore", "minecraft:iron_pickaxe", "minecraft:iron_shovel", "minecraft:iron_sword", "minecraft:iron_trapdoor", "minecraft:lantern", "minecraft:lava_bucket", "minecraft:light_weighted_pressure_plate", "minecraft:lodestone", "minecraft:milk_bucket", "minecraft:minecart", "minecraft:moving_piston", "minecraft:nether_gold_ore", "minecraft:netherite_axe", "minecraft:netherite_block", "minecraft:netherite_boots", "minecraft:netherite_chestplate", "minecraft:netherite_helmet", "minecraft:netherite_hoe", "minecraft:netherite_ingot", "minecraft:netherite_leggings", "minecraft:netherite_pickaxe", "minecraft:netherite_scrap", "minecraft:netherite_shovel", "minecraft:netherite_sword", "minecraft:piston", "minecraft:piston_head", "minecraft:powered_rail", "minecraft:pufferfish_bucket", "minecraft:rail", "minecraft:salmon_bucket", "minecraft:shears", "minecraft:shield", "minecraft:silverfish_spawn_egg", "minecraft:smithing_table", "minecraft:soul_lantern", "minecraft:sticky_piston", "minecraft:stonecutter", "minecraft:tnt_minecart", "minecraft:trapped_chest", "minecraft:tripwire_hook", "minecraft:tropical_fish_bucket", "minecraft:water_bucket", "mod_lavacow:goldenheart", "otg:portalotg_gold", "quark:gold_bars", "quark:gold_button", "quark:golden_apple_crate", "quark:golden_frog_leg", "quark:iron_button", "quark:iron_ladder", "quark:iron_plate", "quark:iron_plate_slab", "quark:iron_plate_stairs", "quark:iron_plate_vertical_slab", "quark:iron_rod", "quark:rusty_iron_plate", "quark:rusty_iron_plate_slab", "quark:rusty_iron_plate_stairs", "quark:rusty_iron_plate_vertical_slab", "simplefarming:golden_habanero", "travelersbackpack:gold", "travelersbackpack:iron", "travelersbackpack:iron_golem"]

