
["Shield mechanics settings"]
	#List of shield items and their damage values. Start the game once to fill these entries with all modded shields automatically. Format: ["Shield name id;shield damage reduction on block; shield passive damage reduction when just held"]E.g. default: ["minecraft:shield;65;15"] this give the minecraft shield 65% damage reduction on block, and 15% passive damage reduction when not blocking but held.To put multiple values seperate them by commas like this:  ["minecraft:shield;65;15", "minecraft:shield;65;15"] 
	shields = ["mod_lavacow:vespa_shield;70;12", "bountifulbaubles:shield_cobalt;50;10", "forestcraft:archaic_shield;77;11", "outvoted:wildfire_shield;68;15", "minecraft:shield;65;15", "forestcraft:honey_keeper;75;17", "forestcraft:prehistoric_shield;85;12", "cataclysm:bulwark_of_the_flame;50;10", "projectdawn:netherite_shield;78;16", "bountifulbaubles:shield_obsidian;50;10", "projectdawn:test_shield;82;14", "bountifulbaubles:shield_ankh;50;10"]
	#Should the altered shield mechanic only affect players
	playerOnly = false
	#Should blocking with a shield set it on cooldown(players only), values are in ticks. 20 ticks = 1 sec
	#Range: 0 ~ 100
	blockCooldown = 5
	#Maximum percent of damage allowed to be blocked. Default:85
	#Range: 0 ~ 100
	maxblockdamagereduction = 85
	#Maximum percent of damage reduction while holding a shield(not blocking). Default:25
	#Range: 0 ~ 100
	maxpassivedamagereduction = 25

